# Generated by Django 5.0.7 on 2024-07-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
